# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [2]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos

conn = sqlite3.connect("Salaries.sqlite")

#Crea el dataframe con los datos del datasets
df = pd.read_sql_query("SELECT * FROM Salaries", conn)

conn.close()

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [4]:
#todo
top_10_salario = df.sort_values(by="TotalPayBenefits", ascending=False).head(10)

top_10_salario = top_10_salario[["EmployeeName", "TotalPayBenefits"]]

print(top_10_salario)

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1               GARY JIMENEZ         538909.28
110531           David Shinn         510732.68
110532            Amy P Hart         479652.21
110533  William J Coaker Jr.         436224.36
72925         Gregory P Suhr         425815.28
72926   Joanne M Hayes-White         422353.40
110534        Gregory P Suhr         418019.22
110535  Joanne M Hayes-White         417435.10
110536       Ellen G Moffatt         415767.94

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [5]:
#todo
#Eliminamos las filas con valores nulos en la columna OvertimePay, y los transformamos en enteros
#los convertimos en 0 si son nulos o no convertibles.
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"], errors="coerce").fillna(0).astype(int)

#Mostramos los empleados que tienen más de 50 mil por hs extras.
df[df["OvertimePay"] > 50000 ]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062,134426.14,None,315981.05,315981.05,2011,None,San Francisco,None
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362,40132.23,None,303427.55,303427.55,2011,None,San Francisco,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118288,118289,Francisco A Arce,Transit Operator,66628.53,51625,1178.11,34801.17,119432.06,154233.23,2014,None,San Francisco,FT
118342,118343,Felix Pagatpatan,Transit Operator,65620.85,52550,1407.74,34350.93,119579.12,153930.05,2014,None,San Francisco,FT
119450,119451,Bobby Jones,Track Maintenance Worker,60263.3,50265,8188.87,28210.55,118717.40,146927.95,2014,None,San Francisco,FT
119607,119608,Hung V Nguyen,Diagnostic Imaging Tech I,44939.15,74935,6496.58,19401.42,126371.69,145773.11,2014,None,San Francisco,PT
120204,120205,Girma-Worku Zeleke,Parking Control Officer,59555.2,54738,397.04,26938.47,114690.60,141629.07,2014,None,San Francisco,FT

3. **Contar cuántos empleados únicos hay por año**

In [ ]:
#todo
# utilizando .nunique() cuenta los valores únicos en la columna "EmployeeName" por cada año

empleados_unicos = df.groupby('Year')['EmployeeName'].nunique()

print("La cantidad de empleados únicos por año son: ")
print(empleados_unicos)

Cantidad de empleados únicos por año:
Year
2011    33878
2012    34349
2013    36150
2014    36684
Name: EmployeeName, dtype: int64

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [ ]:
#todo
#Filtramos para encon0trar los cargos únicos
cargos_unicos = df["JobTitle"].unique()
print("Cargos únicos: ")
print(cargos_unicos)


# Ahora buscamos los 5 más comunes. 

# Seleccionamos la columna "JobTitle" y contamos cuantas veces 
# aparece cada cargo usando value_counts()

cargos_mas_comunes = df["JobTitle"].value_counts().head(5)

print("\nLos cargos más comunes son: ")
print(cargos_mas_comunes)

Cargos únicos:
['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY'
 'CAPTAIN III (POLICE DEPARTMENT)' 'WIRE ROPE CABLE MAINTENANCE MECHANIC'
 ... 'Conversion' 'Cashier 3' 'Not provided']

Cargos más comunes:
JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo
# Agrupamos el salario por año, con el metodo mean obtenemos promedio y 
# con astype(int) lo convertimos a enteros.

salario_promedio_año = df.groupby("Year")["TotalPay"].mean().astype(int)

print("El salario promedio por año es: ")
print(salario_promedio_año)

Salario promedio por año:
Year
2011    71744
2012    74113
2013    77611
2014    75463
Name: TotalPay, dtype: int64

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [11]:
#todo

# Con el metodo to_csv() guardamos el dataframe en un archivo CSV.

df.to_csv("Salaries.csv", index=False)

#Con el metodo tail(10) mostramos las últimas 10 filas del dataframe
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,0,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,0,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148651,148652,Not provided,Not provided,Not Provided,0,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148652,148653,Not provided,Not provided,Not Provided,0,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0,-618.13,0.00,-618.13,-618.13,2014,None,San Francisco,PT